<?xml version="1.0"?>
<robot name="agv"
  xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="agv_base" params="simulation_mode">

    <xacro:property name="wheel_radius" value="0.08" />
    <xacro:property name="wheel_width" value="0.06" />
    <xacro:property name="wheel_ygap" value="0.035" />
    <xacro:property name="wheel_zoff" value="0.04" />
    <xacro:property name="wheel_xoff" value="0.0" />
    <xacro:property name="caster_xoff" value="0.3" />

    <xacro:macro name="box_inertia" params="m w h d">
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}" />
        <mass value="${m}" />
        <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}" />
      </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <mass value="${m}" />
        <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0" iyy="${(m/12) * (3*r*r + h*h)}" iyz="0" izz="${(m/2) * (r*r)}" />
      </inertial>
    </xacro:macro>
    <xacro:if value="${simulation_mode}">
      <material name="green_disinfector">
        <color rgba="0.25 0.4 0.0 0.70" />
      </material>
    </xacro:if>

    <link name="base_link">
      <xacro:if value="${simulation_mode}">
        <visual cast_shadows="false">
          <origin xyz="0.0 0.0 ${-(wheel_radius + (base_height/2))}" rpy="0 0 0.0" />
          <geometry>
            <mesh filename="file://$(find agv_core)/meshes/agv_chassis.dae" />
          </geometry>
          <!-- <material name="green_disinfector" /> -->
        </visual>
      </xacro:if>
      <collision>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="15.0" r="${base_radius}" h="${base_height}" />
    </link>

    <xacro:if value="${simulation_mode}">
      <gazebo reference="base_link">
        <material>Gazebo/green_disinfector</material>
      </gazebo>
    </xacro:if>

    <link name="base_footprint">
      <xacro:box_inertia m="0" w="0" d="0" h="0" />
    </link>

    <joint name="base_joint" type="fixed">
      <parent link="base_link" />
      <child link="base_footprint" />
      <origin xyz="0.0 0.0 ${-(wheel_radius + (base_height/2))}" rpy="0 0 0" />
    </joint>
  </xacro:macro>

</robot>